"""
================================================================================
AUDIT & RECOMPUTE — Flower classification, 5-algorithm ablation study
================================================================================

Purpose
-------
Every previous round of results (evaluation_summary_*.txt, comparison_*.txt)
was generated by separate scripts run independently at different times, and
they disagree with each other in at least two confirmed places (Group B vs
Group C accuracy, and duplicate/ambiguous seed labeling for Group B').

This script recomputes EVERYTHING from scratch, in one single pass, directly
from the saved checkpoints (best_model*.pth), so there is exactly one source
of truth going forward:

    1. Rebuild the canonical test set (same split logic as train_A/B/C.py:
       test_split=0.1, val_split=0.2, manual_seed(42) — confirmed identical
       across all 5 groups by diffing prepare_dataloaders() in train_A.py,
       train_B.py, train_C.py).
    2. For each of the 5 algorithms x 3 seeds (15 checkpoints total):
         - Load the correct architecture
         - Load the checkpoint weights
         - Run a SANITY CHECK that does not trust the filename/folder:
             (a) trainable-parameter fraction must match what the
                 architecture predicts for its group
             (b) backbone weight drift from the original ImageNet-pretrained
                 ResNet50 must be ~0 for frozen groups (3, 4) and
                 non-trivial for the fine-tuned group (5). This is the check
                 that would have caught the original Group B/C mix-up
                 immediately, because it only depends on the WEIGHTS
                 actually stored in the .pth file, not on any label.
         - Evaluate on the test set: accuracy, precision/recall/F1
           (macro + weighted), confusion matrix, per-class error rate
    3. Aggregate mean +/- std per algorithm across the 3 seeds.
    4. Run all 10 pairwise comparisons (paired t-test across the 3 shared
       seeds — since the same seeds 42/123/999 were reused for every
       algorithm, a paired test is the statistically correct choice here;
       switch PAIRED_TEST=False below if you specifically want independent
       t-tests instead).
    5. Write one consolidated, unambiguous results directory.

Before running
--------------
Edit the CONFIG block below:
    - CODE_ROOT: path to the "code/" folder from architecture.txt
    - DATA_ROOT: path to "code/data/5_classes/"
    - OUTPUT_DIR: where to write results (created if missing)

Requires: torch, torchvision, numpy, pandas, scipy, scikit-learn, Pillow
================================================================================
"""

import os
import glob
import json
from dataclasses import dataclass, field
from typing import List, Tuple, Optional, Dict

import numpy as np
import pandas as pd
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader, random_split
from torchvision import transforms, models
from PIL import Image
from sklearn.metrics import (
    accuracy_score, precision_recall_fscore_support, confusion_matrix
)
from scipy import stats
from itertools import combinations

# ==============================================================================
# CONFIG — EDIT THESE PATHS
# ==============================================================================

CODE_ROOT = "C:/Flowers Classification/code"                   # folder containing src1/, src2/, ...
DATA_ROOT = os.path.join(CODE_ROOT, "data", "5_classes")
OUTPUT_DIR = "./audit_results"

SEEDS = [42, 123, 999]
IMAGE_SIZE = (224, 224)
BATCH_SIZE = 32
DEVICE = "cuda" if torch.cuda.is_available() else "cpu"

# Paired t-test is correct here because the SAME 3 seeds (42, 123, 999) were
# reused across every algorithm (confirmed from train_C.py / train_A.py).
# Set to False for independent-samples t-tests instead.
PAIRED_TEST = True

# Backbone-drift threshold (L2 norm of weight difference vs fresh ImageNet
# ResNet50, summed over a few early+late conv layers). Frozen backbones
# should read ~0.0; fine-tuned backbones should read clearly > 0.
DRIFT_FLAG_THRESHOLD = 1e-3


# ==============================================================================
# ALGORITHM REGISTRY
# ==============================================================================
# model_type: "cnn" (src1/src2, FlowerCNN) or "resnet" (src3/4/5, FlowerResNet)
# freeze_backbone: what the architecture is SUPPOSED to do (used to predict
#   expected trainable %, then checked against the checkpoint's actual weights)

@dataclass
class AlgoSpec:
    algo_id: int
    name: str
    src_dir: str
    checkpoint_filename: str
    model_type: str        # "cnn" | "resnet"
    freeze_backbone: bool   # expected, for sanity-check purposes only
    augmentation: bool


ALGOS: List[AlgoSpec] = [
    AlgoSpec(1, "CNN from scratch (baseline)", "src1", "best_model.pth",
             "cnn", freeze_backbone=False, augmentation=False),
    AlgoSpec(2, "CNN improved + augmentation (Group A)", "src2", "best_model_A.pth",
             "cnn", freeze_backbone=False, augmentation=True),
    AlgoSpec(3, "Transfer learning, frozen + aug (Group B)", "src3", "best_model_B.pth",
             "resnet", freeze_backbone=True, augmentation=True),
    AlgoSpec(4, "Transfer learning, frozen, no aug (Group B')", "src4", "best_model_B_P.pth",
             "resnet", freeze_backbone=True, augmentation=False),
    AlgoSpec(5, "Fine-tuning, backbone unfrozen (Group C)", "src5", "best_model_C.pth",
             "resnet", freeze_backbone=False, augmentation=True),
]

CLASS_NAMES = ["Lilly", "Lotus", "Orchid", "Sunflower", "Tulip"]  # alphabetical
# (confirmed: LoadData.discover_classes() uses sorted(os.listdir(...)) in every
#  load_data*.py variant — identical across all 5 groups)


# ==============================================================================
# MODEL DEFINITIONS
# (reconstructed to match model.py / model_A.py / model_B.py / model_B_p.py /
#  model_C.py exactly — same layer names, so state_dict keys line up)
# ==============================================================================

class FlowerCNN(nn.Module):
    """From-scratch CNN — identical in model.py and model_A.py."""

    def __init__(self, num_classes: int = 5):
        super().__init__()
        self.conv1 = nn.Sequential(
            nn.Conv2d(3, 16, kernel_size=3, padding=1), nn.BatchNorm2d(16),
            nn.ReLU(), nn.MaxPool2d(2, 2)
        )
        self.conv2 = nn.Sequential(
            nn.Conv2d(16, 32, kernel_size=3, padding=1), nn.BatchNorm2d(32),
            nn.ReLU(), nn.MaxPool2d(2, 2)
        )
        self.conv3 = nn.Sequential(
            nn.Conv2d(32, 64, kernel_size=3, padding=1), nn.BatchNorm2d(64),
            nn.ReLU(), nn.MaxPool2d(2, 2)
        )
        self.conv4 = nn.Sequential(
            nn.Conv2d(64, 128, kernel_size=3, padding=1), nn.BatchNorm2d(128),
            nn.ReLU(), nn.MaxPool2d(2, 2)
        )
        self.classifier = nn.Sequential(
            nn.Flatten(), nn.Linear(128 * 14 * 14, 256), nn.ReLU(),
            nn.Dropout(0.5), nn.Linear(256, num_classes)
        )

    def forward(self, x):
        x = self.conv1(x); x = self.conv2(x); x = self.conv3(x); x = self.conv4(x)
        return self.classifier(x)


class FlowerResNet(nn.Module):
    """
    ResNet50 wrapper — structurally identical across model_B.py, model_B_p.py,
    and model_C.py (only difference between them is whether requires_grad is
    set to False on the backbone at init time, which does NOT change the
    state_dict keys). One class covers Groups B, B', and C.
    """

    def __init__(self, num_classes: int = 5, pretrained: bool = True,
                 freeze_backbone: bool = True):
        super().__init__()
        weights = models.ResNet50_Weights.IMAGENET1K_V2 if pretrained else None
        self.backbone = models.resnet50(weights=weights)
        if freeze_backbone:
            for p in self.backbone.parameters():
                p.requires_grad = False
        in_features = self.backbone.fc.in_features
        self.backbone.fc = nn.Sequential(
            nn.Linear(in_features, 256), nn.ReLU(),
            nn.Dropout(0.5), nn.Linear(256, num_classes)
        )

    def forward(self, x):
        return self.backbone(x)


def build_model(spec: AlgoSpec) -> nn.Module:
    if spec.model_type == "cnn":
        return FlowerCNN(num_classes=len(CLASS_NAMES))
    elif spec.model_type == "resnet":
        return FlowerResNet(num_classes=len(CLASS_NAMES), pretrained=True,
                             freeze_backbone=spec.freeze_backbone)
    else:
        raise ValueError(f"Unknown model_type: {spec.model_type}")


# ==============================================================================
# DATA LOADING (identical to load_data.py / load_data_A.py / load_data_B.py /
# load_data_B_p.py / load_data_C.py — verified byte-identical except trailing
# whitespace, and load_data_C.py differs only in a trailing newline)
# ==============================================================================

class LoadData:
    def __init__(self, data_path: str, image_size: Tuple[int, int] = (224, 224)):
        self.data_path = data_path
        self.image_size = image_size
        self.classes: List[str] = []

    def discover_classes(self) -> List[str]:
        self.classes = sorted(
            d for d in os.listdir(self.data_path)
            if os.path.isdir(os.path.join(self.data_path, d))
        )
        return self.classes

    def find_images(self, extensions=('*.jpg', '*.jpeg', '*.png', '*.gif', '*.bmp')) -> List[str]:
        paths = []
        for ext in extensions:
            paths.extend(glob.glob(os.path.join(self.data_path, '*', ext)))
        return sorted(paths)

    def load_image(self, path: str) -> Optional[np.ndarray]:
        try:
            img = Image.open(path).convert('RGB').resize(self.image_size, Image.LANCZOS)
            return np.array(img, dtype=np.uint8)
        except Exception as e:
            print(f"  [warn] failed to load {path}: {e}")
            return None

    def load_all(self) -> Tuple[np.ndarray, np.ndarray, List[str]]:
        self.discover_classes()
        class_to_idx = {c: i for i, c in enumerate(self.classes)}
        images, labels = [], []
        for p in self.find_images():
            cls = os.path.basename(os.path.dirname(p))
            arr = self.load_image(p)
            if arr is not None:
                images.append(arr)
                labels.append(class_to_idx[cls])
        return (np.array(images, dtype=np.uint8),
                np.array(labels, dtype=np.int64), self.classes)


class FlowerDataset(Dataset):
    def __init__(self, images, labels, transform=None):
        self.images, self.labels, self.transform = images, labels, transform

    def __len__(self):
        return len(self.images)

    def __getitem__(self, idx):
        img = Image.fromarray(self.images[idx])
        if self.transform:
            img = self.transform(img)
        return img, self.labels[idx]


def get_eval_transform(image_size=(224, 224)):
    """Val/test transform — identical across all groups: resize + ImageNet norm."""
    return transforms.Compose([
        transforms.Resize(image_size),
        transforms.ToTensor(),
        transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225]),
    ])


def build_canonical_test_set(images: np.ndarray, labels: np.ndarray,
                              val_split: float = 0.2, test_split: float = 0.1
                              ) -> DataLoader:
    """
    Reproduces prepare_dataloaders()'s split exactly (verified identical,
    modulo comments, across train_A.py / train_B.py / train_C.py):
    manual_seed(42), test_split=0.1, val_split=0.2, index-based random_split.
    Only the test set is needed here.
    """
    total = len(images)
    test_size = int(total * test_split)
    val_size = int(total * val_split)
    train_size = total - val_size - test_size

    _, _, test_indices = random_split(
        range(total), [train_size, val_size, test_size],
        generator=torch.Generator().manual_seed(42)
    )

    test_images = images[test_indices.indices]
    test_labels = labels[test_indices.indices]

    test_ds = FlowerDataset(test_images, test_labels,
                             transform=get_eval_transform(IMAGE_SIZE))
    return DataLoader(test_ds, batch_size=BATCH_SIZE, shuffle=False,
                       num_workers=4, pin_memory=(DEVICE == "cuda"))


# ==============================================================================
# SANITY CHECKS — do not trust filenames/folders, verify from the weights
# ==============================================================================

def count_parameters(model: nn.Module) -> Dict[str, float]:
    total = sum(p.numel() for p in model.parameters())
    trainable = sum(p.numel() for p in model.parameters() if p.requires_grad)
    return {"total": total, "trainable": trainable,
            "trainable_percent": 100 * trainable / total}


def backbone_drift(loaded_model: nn.Module) -> Optional[float]:
    """
    For ResNet-based groups only. Compares a handful of backbone conv layers
    against a FRESH ImageNet-pretrained ResNet50 (never touched by any
    training). If the checkpoint's backbone is frozen during training, this
    should be ~0.0. If fine-tuned, it should be clearly > 0.

    This check depends only on the numbers stored in the .pth file — not on
    which folder it came from or what it's named — so it is the definitive
    way to tell a Group B/B' checkpoint apart from a Group C checkpoint.
    """
    if not hasattr(loaded_model, "backbone"):
        return None
    fresh = models.resnet50(weights=models.ResNet50_Weights.IMAGENET1K_V2)
    fresh.eval()

    layers_to_check = ["conv1.weight", "layer1.0.conv1.weight", "layer4.2.conv3.weight"]
    total_diff = 0.0
    with torch.no_grad():
        for layer_name in layers_to_check:
            loaded_param = dict(loaded_model.backbone.named_parameters())[layer_name]
            fresh_param = dict(fresh.named_parameters())[layer_name]
            total_diff += (loaded_param.cpu() - fresh_param).norm().item()
    return total_diff


def load_checkpoint_into(model: nn.Module, ckpt_path: str) -> nn.Module:
    ckpt = torch.load(ckpt_path, map_location=DEVICE)
    state_dict = ckpt["model_state_dict"] if isinstance(ckpt, dict) and "model_state_dict" in ckpt else ckpt
    model.load_state_dict(state_dict)
    model.to(DEVICE)
    model.eval()
    return model


# ==============================================================================
# EVALUATION
# ==============================================================================

def evaluate(model: nn.Module, test_loader: DataLoader) -> Dict:
    all_preds, all_labels = [], []
    with torch.no_grad():
        for images, labels in test_loader:
            images = images.to(DEVICE)
            outputs = model(images)
            _, preds = torch.max(outputs, 1)
            all_preds.extend(preds.cpu().numpy())
            all_labels.extend(labels.numpy())

    all_preds = np.array(all_preds)
    all_labels = np.array(all_labels)

    acc = accuracy_score(all_labels, all_preds) * 100
    p_macro, r_macro, f1_macro, _ = precision_recall_fscore_support(
        all_labels, all_preds, average="macro", zero_division=0)
    p_weighted, r_weighted, f1_weighted, _ = precision_recall_fscore_support(
        all_labels, all_preds, average="weighted", zero_division=0)

    cm = confusion_matrix(all_labels, all_preds, labels=list(range(len(CLASS_NAMES))))
    per_class_error = {}
    for i, cls in enumerate(CLASS_NAMES):
        support = cm[i].sum()
        errors = support - cm[i, i]
        per_class_error[cls] = 100 * errors / support if support > 0 else float("nan")

    return {
        "accuracy": acc,
        "precision_macro": p_macro * 100, "recall_macro": r_macro * 100, "f1_macro": f1_macro * 100,
        "precision_weighted": p_weighted * 100, "recall_weighted": r_weighted * 100, "f1_weighted": f1_weighted * 100,
        "confusion_matrix": cm,
        "per_class_error": per_class_error,
        "test_set_size": len(all_labels),
    }


# ==============================================================================
# MAIN PIPELINE
# ==============================================================================

def main():
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    confmat_dir = os.path.join(OUTPUT_DIR, "confusion_matrices")
    os.makedirs(confmat_dir, exist_ok=True)

    print("=" * 70)
    print("STEP 1 — Loading raw images and rebuilding canonical test set")
    print("=" * 70)
    loader = LoadData(DATA_ROOT, image_size=IMAGE_SIZE)
    images, labels, discovered_classes = loader.load_all()
    assert discovered_classes == CLASS_NAMES, (
        f"Class order mismatch! Got {discovered_classes}, expected {CLASS_NAMES}. "
        f"Do not proceed — every checkpoint below assumes this exact index mapping."
    )
    test_loader = build_canonical_test_set(images, labels)
    print(f"Canonical test set size: {len(test_loader.dataset)} "
          f"(expected 499 based on prior logs)")
    if len(test_loader.dataset) != 499:
        print("  [FLAG] Test set size does not match the 499 seen in prior logs — "
              "investigate before trusting any comparison below.")

    print()
    print("=" * 70)
    print("STEP 2 — Loading each checkpoint, sanity-checking, evaluating")
    print("=" * 70)

    per_run_rows = []
    flags = []

    for spec in ALGOS:
        for seed in SEEDS:
            ckpt_path = os.path.join(
                CODE_ROOT, spec.src_dir, "checkpoints",
                f"run_seed{seed}", spec.checkpoint_filename
            )
            print(f"\n--- Algo {spec.algo_id} ({spec.name}) — seed {seed} ---")
            print(f"Loading: {ckpt_path}")

            if not os.path.exists(ckpt_path):
                msg = f"[FLAG] Missing checkpoint: {ckpt_path}"
                print(f"  {msg}")
                flags.append(msg)
                continue

            model = build_model(spec)
            model = load_checkpoint_into(model, ckpt_path)

            # --- Sanity check 1: trainable parameter fraction ---
            param_stats = count_parameters(model)
            expected_frozen = spec.freeze_backbone
            actual_looks_frozen = param_stats["trainable_percent"] < 10.0  # head-only ballpark
            if expected_frozen != actual_looks_frozen:
                msg = (f"[FLAG] Algo {spec.algo_id} seed {seed}: expected "
                       f"freeze_backbone={expected_frozen} but trainable% is "
                       f"{param_stats['trainable_percent']:.1f}% — architecture "
                       f"instantiation may not match how this checkpoint was trained.")
                print(f"  {msg}")
                flags.append(msg)

            # --- Sanity check 2: backbone weight drift (only meaningful for resnet) ---
            drift = backbone_drift(model) if spec.model_type == "resnet" else None
            if drift is not None:
                is_frozen_group = spec.algo_id in (3, 4)
                if is_frozen_group and drift > DRIFT_FLAG_THRESHOLD:
                    msg = (f"[FLAG] Algo {spec.algo_id} seed {seed}: backbone should be "
                           f"FROZEN but weight drift from pretrained ResNet50 = {drift:.6f} "
                           f"(expected ~0). This checkpoint may actually belong to a "
                           f"fine-tuned group.")
                    print(f"  {msg}")
                    flags.append(msg)
                elif spec.algo_id == 5 and drift < DRIFT_FLAG_THRESHOLD:
                    msg = (f"[FLAG] Algo 5 seed {seed}: backbone should be FINE-TUNED "
                           f"(unfrozen) but weight drift from pretrained ResNet50 = "
                           f"{drift:.6f} (~0, i.e. it looks frozen). This checkpoint may "
                           f"not actually be fine-tuned.")
                    print(f"  {msg}")
                    flags.append(msg)
                print(f"  Backbone drift from ImageNet-pretrained: {drift:.6f}")

            # --- Evaluate ---
            results = evaluate(model, test_loader)
            print(f"  Accuracy: {results['accuracy']:.2f}%  |  "
                  f"F1-macro: {results['f1_macro']:.2f}%  |  "
                  f"Test size: {results['test_set_size']}")

            # Save confusion matrix, unambiguously named
            cm_path = os.path.join(confmat_dir, f"confmat_algo{spec.algo_id}_seed{seed}.csv")
            pd.DataFrame(results["confusion_matrix"], index=CLASS_NAMES, columns=CLASS_NAMES) \
                .to_csv(cm_path)

            row = {
                "algo_id": spec.algo_id, "algo_name": spec.name, "seed": seed,
                "accuracy": results["accuracy"],
                "precision_macro": results["precision_macro"],
                "recall_macro": results["recall_macro"],
                "f1_macro": results["f1_macro"],
                "precision_weighted": results["precision_weighted"],
                "recall_weighted": results["recall_weighted"],
                "f1_weighted": results["f1_weighted"],
                "test_set_size": results["test_set_size"],
                "trainable_percent": param_stats["trainable_percent"],
                "backbone_drift": drift,
            }
            for cls, err in results["per_class_error"].items():
                row[f"error_{cls}"] = err
            per_run_rows.append(row)

    per_run_df = pd.DataFrame(per_run_rows)
    per_run_csv = os.path.join(OUTPUT_DIR, "per_run_metrics.csv")
    per_run_df.to_csv(per_run_csv, index=False)
    print(f"\nSaved per-run metrics: {per_run_csv}")

    print()
    print("=" * 70)
    print("STEP 3 — Aggregating mean +/- std per algorithm")
    print("=" * 70)

    metric_cols = ["accuracy", "precision_macro", "recall_macro", "f1_macro",
                   "precision_weighted", "recall_weighted", "f1_weighted"]
    agg = per_run_df.groupby(["algo_id", "algo_name"])[metric_cols].agg(["mean", "std"])
    agg.columns = ["_".join(c) for c in agg.columns]
    agg = agg.reset_index()
    agg_csv = os.path.join(OUTPUT_DIR, "aggregated_summary.csv")
    agg.to_csv(agg_csv, index=False)
    print(agg.to_string(index=False))
    print(f"\nSaved aggregated summary: {agg_csv}")

    print()
    print("=" * 70)
    print(f"STEP 4 — Pairwise statistical tests "
          f"({'paired' if PAIRED_TEST else 'independent'} t-test)")
    print("=" * 70)

    pairwise_rows = []
    for (a_id, b_id) in combinations(sorted(per_run_df["algo_id"].unique()), 2):
        a_name = per_run_df.loc[per_run_df.algo_id == a_id, "algo_name"].iloc[0]
        b_name = per_run_df.loc[per_run_df.algo_id == b_id, "algo_name"].iloc[0]
        for metric in ["accuracy", "f1_macro", "precision_macro", "recall_macro"]:
            a_vals = per_run_df.loc[per_run_df.algo_id == a_id]\
                .sort_values("seed")[metric].values
            b_vals = per_run_df.loc[per_run_df.algo_id == b_id]\
                .sort_values("seed")[metric].values
            if len(a_vals) != len(b_vals) or len(a_vals) < 2:
                continue
            if PAIRED_TEST:
                t_stat, p_val = stats.ttest_rel(a_vals, b_vals)
            else:
                t_stat, p_val = stats.ttest_ind(a_vals, b_vals)
            pairwise_rows.append({
                "algo_a": a_id, "name_a": a_name, "mean_a": a_vals.mean(), "std_a": a_vals.std(ddof=1),
                "algo_b": b_id, "name_b": b_name, "mean_b": b_vals.mean(), "std_b": b_vals.std(ddof=1),
                "metric": metric, "t_stat": t_stat, "p_value": p_val,
                "significant_at_0.05": p_val < 0.05,
            })

    pairwise_df = pd.DataFrame(pairwise_rows)
    pairwise_csv = os.path.join(OUTPUT_DIR, "pairwise_tests.csv")
    pairwise_df.to_csv(pairwise_csv, index=False)
    print(f"Saved pairwise tests: {pairwise_csv}")

    print()
    print("=" * 70)
    print("STEP 5 — Flags raised during this run")
    print("=" * 70)
    if flags:
        for f in flags:
            print(f" - {f}")
    else:
        print("No inconsistencies detected. All checkpoints matched their expected group.")

    flags_path = os.path.join(OUTPUT_DIR, "flags.txt")
    with open(flags_path, "w", encoding="utf-8") as fh:
        fh.write("\n".join(flags) if flags else "No inconsistencies detected.\n")
    print(f"\nSaved flags: {flags_path}")

    print()
    print("Done. All outputs in:", os.path.abspath(OUTPUT_DIR))


if __name__ == "__main__":
    main()
